# -*- coding: utf-8 -*-
"""ExercíciosPython_Luisfernando_B_06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RP-US4uHcBJz5KTUY5B9tg__T6UAU4Dp

Exercicio 1 -  Aqui basta você utilizar o comando print() que exibe tal informação na tela
"""

print("hello, Word")

"""Exercicio 2 -
Recebemos dois valores, com o float conseguimos trabalhar com números inteiros

"""

numero = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

soma = numero + numero2

print("A Soma dos números é:", soma)

"""Exercicio 3 -

Aqui é bem simples, o math.pi fornece o calor de tt, raio ** 2  elava o raio ao quadrado, e o :.2
"""

import math

raio = float(input("Digite o raio do círculo: "))

area = math.pi * raio ** 2

print(f"A área do círculo é: {area:.2f}")

"""Exercecio 4 -
A forma utilizada é


"""

celsius = float(input("Digite a temperatura em Celsius: "))

fahrenheit = celsius * 9 / 5 + 32

print(f"A temperatura em Fahrenheit é: {fahrenheit:.2f} °F")

"""Exercicio 5

Utilizamos o for para repetir o cálculos para os números de 1 até 10
"""

numero = int(input("Digite um número para ver sua tabuada: "))

for multiplicador in range(1, 11):
    resultado = numero * multiplicador
    print(f"{numero} x {multiplicador} = {resultado}")

"""Exercicio 6 - O terceiro range() ira definir a contagem e avançar de dois em dois .

"""

print("Números pares de 1 a 20:")

for numero in range(2, 21, 2):
    print(numero)

"""Exercicio 7 - O % calcula o resto da divisão, por exemplo se for dividido por 2 for 0 o número é par

"""

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
    print("O número é par.")
else:
    print("O número é ímpar.")

"""Exercicio 8 - .lower() transforma as letras em minúsculas, [::-1] ele inverte a string .

"""

palavra = input("Digite uma palavra: ").lower()

palavra_invertida = palavra[::-1]

if palavra == palavra_invertida:
    print("A palavra é um palíndromo.")
else:
    print("A palavra não é um palíndromo.")

"""Exercicio 9 - O fatorial do número é a multiplicação dele por todos os inteiros positivos anteriores .

"""

numero = int(input("Digite um número inteiro não negativo: "))

if numero < 0:
    print("Não existe fatorial de número negativo.")
else:
    fatorial = 1

    for valor in range(1, numero + 1):
        fatorial = fatorial * valor

    print(f"O fatorial de {numero} é {fatorial}.")

"""Exercicio 10 - Na sequencia de cada número é a soma dos dois números anteriores."""

primeiro = 0
segundo = 1

print("Os primeiros 10 números da sequência de Fibonacci são:")

for contador in range(10):
    print(primeiro)

    proximo = primeiro + segundo
    primeiro = segundo
    segundo = proximo

"""Exercicio 11- Aqui usamos o max() para encontrar o maior valor e min para encontrar o menor valor.

"""

numeros = [15, 8, 32, 4, 19, 27]

print("Lista:", numeros)
print("Maior número:", max(numeros))
print("Menor número:", min(numeros))

"""Exercicio 12 - O codigo percorre cada caractere do texto e utilizei um dicionario para guardar quantas vezes ele aparece."""

texto = input("Digite uma frase: ")

contagem = {}

for caractere in texto:
    if caractere in contagem:
        contagem[caractere] += 1
    else:
        contagem[caractere] = 1

print("Quantidade de cada caractere:")

for caractere, quantidade in contagem.items():
    print(f"{repr(caractere)}: {quantidade}")

"""Exercicio 13 - Utlizei o metodo .sort que ordena os elementos da propria lista em ordem crescente"""

numeros = [14, 5, 9, 2, 20, 7]

print("Lista original:", numeros)

numeros.sort()

print("Lista ordenada:", numeros)

"""Exercicio 14 - Aqui coloquei a variavel soma que começa com zero e recebe cada valor da lista"""

numeros = [10, 20, 30, 40, 50]

soma = 0

for numero in numeros:
    soma += numero

print("Lista:", numeros)
print("A soma dos elementos é:", soma)

"""Exercicio 15 - Para calculcar a media eu fiz a divisao da soma dos números pela quantidade de elementos"""

numeros = [7, 8, 6, 9, 10]

soma = sum(numeros)
quantidade = len(numeros)
media = soma / quantidade

print("Lista:", numeros)
print(f"A média é: {media:.2f}")

"""Exercicio 16 - USei o metodo [::-1] que percorre o string do final para o começo"""

texto = input("Digite um texto: ")

texto_invertido = texto[::-1]

print("Texto original:", texto)
print("Texto invertido:", texto_invertido)

"""Exercicio 17 - Aqui utilizei o dicicionario para contar a frequencia de cada palavra na frase

"""

texto = input("Digite uma frase: ").lower()

palavras = texto.split()
frequencia = {}

for palavra in palavras:
    if palavra in frequencia:
        frequencia[palavra] += 1
    else:
        frequencia[palavra] = 1

print("Frequência das palavras:")

for palavra, quantidade in frequencia.items():
    print(f"{palavra}: {quantidade}")

"""Exercicio 18 - Usei a logica para descobir se é primo, o maior que 1 só pode ser divido por e por ele mesmo.

"""

numero = int(input("Digite um número inteiro: "))

eh_primo = True

if numero <= 1:
    eh_primo = False
else:
    for divisor in range(2, int(numero ** 0.5) + 1):
        if numero % divisor == 0:
            eh_primo = False
            break

if eh_primo:
    print(f"{numero} é um número primo.")
else:
    print(f"{numero} não é um número primo.")

"""Exercicio 19 - Aqui o modulo random gera um número aleatório entre 1 e 10"""

import random

numero_secreto = random.randint(1, 10)
tentativas = 0
palpite = 0

print("Tente adivinhar o número entre 1 e 100.")

while palpite != numero_secreto:
    palpite = int(input("Digite seu palpite: "))
    tentativas += 1

    if palpite < numero_secreto:
        print("O número secreto é maior.")
    elif palpite > numero_secreto:
        print("O número secreto é menor.")
    else:
        print(f"Parabéns! Você acertou em {tentativas} tentativas.")

"""Exercicio 20 - Aqui fiz que as linhas da matriz original tornam-se colunas"""

matriz = [
    [1, 2, 3],
    [4, 5, 6]
]

transposta = []

quantidade_colunas = len(matriz[0])
quantidade_linhas = len(matriz)

for coluna in range(quantidade_colunas):
    nova_linha = []

    for linha in range(quantidade_linhas):
        nova_linha.append(matriz[linha][coluna])

    transposta.append(nova_linha)

print("Matriz original:")

for linha in matriz:
    print(linha)

print("Matriz transposta:")

for linha in transposta:
    print(linha)

"""Exercicio 21 - A busca binaria procura um elemento em uma lista ordenada, com isso dividindo a área de busca pela metade a cada repetição ."""

def busca_binaria(lista, elemento):
    inicio = 0
    fim = len(lista) - 1

    while inicio <= fim:
        meio = (inicio + fim) // 2

        if lista[meio] == elemento:
            return meio
        elif lista[meio] < elemento:
            inicio = meio + 1
        else:
            fim = meio - 1

    return -1


numeros = [2, 5, 8, 12, 16, 23, 38, 45]
procurado = int(input("Digite o número que deseja procurar: "))

posicao = busca_binaria(numeros, procurado)

if posicao != -1:
    print(f"O número foi encontrado na posição {posicao}.")
else:
    print("O número não foi encontrado.")

"""Exercicio 22 - o cifra ele substitui cada letra por outra que esta em posições a frente no alfabeto."""

def criptografar(mensagem, deslocamento):
    mensagem_cifrada = ""

    for caractere in mensagem:
        if caractere.isalpha():
            if caractere.isupper():
                codigo_inicial = ord("A")
            else:
                codigo_inicial = ord("a")

            posicao = ord(caractere) - codigo_inicial
            nova_posicao = (posicao + deslocamento) % 26
            nova_letra = chr(codigo_inicial + nova_posicao)

            mensagem_cifrada += nova_letra
        else:
            mensagem_cifrada += caractere

    return mensagem_cifrada


mensagem = input("Digite a mensagem: ")
deslocamento = int(input("Digite o deslocamento: "))

resultado = criptografar(mensagem, deslocamento)

print("Mensagem criptografada:", resultado)

"""Exercicio 23 - Para descriptografar eu apenas fiz no sentido contrario"""

def descriptografar(mensagem, deslocamento):
    mensagem_original = ""

    for caractere in mensagem:
        if caractere.isalpha():
            if caractere.isupper():
                codigo_inicial = ord("A")
            else:
                codigo_inicial = ord("a")

            posicao = ord(caractere) - codigo_inicial
            nova_posicao = (posicao - deslocamento) % 26
            nova_letra = chr(codigo_inicial + nova_posicao)

            mensagem_original += nova_letra
        else:
            mensagem_original += caractere

    return mensagem_original


mensagem_cifrada = input("Digite a mensagem criptografada: ")
deslocamento = int(input("Digite o deslocamento utilizado: "))

resultado = descriptografar(mensagem_cifrada, deslocamento)

print("Mensagem original:", resultado)

"""Exercicio 24 - Aqui usei a função true , quando os digitos calculados são iguais aos dois ultimos digitos do cpf ele retorna."""

def validar_cpf(cpf):
    cpf = "".join(caractere for caractere in cpf if caractere.isdigit())

    if len(cpf) != 11:
        return False

    if cpf == cpf[0] * 11:
        return False

    soma = 0

    for indice in range(9):
        soma += int(cpf[indice]) * (10 - indice)

    resto = soma % 11

    if resto < 2:
        primeiro_digito = 0
    else:
        primeiro_digito = 11 - resto

    soma = 0

    for indice in range(10):
        soma += int(cpf[indice]) * (11 - indice)

    resto = soma % 11

    if resto < 2:
        segundo_digito = 0
    else:
        segundo_digito = 11 - resto

    return (
        primeiro_digito == int(cpf[9])
        and segundo_digito == int(cpf[10])
    )


cpf = input("Digite um CPF: ")

if validar_cpf(cpf):
    print("CPF válido.")
else:
    print("CPF inválido.")

"""Exercicio 25 - Os numeros serao separados em positivos e negativos em zero"""

numeros = [10, -5, 0, 8, -2, 0, 15, -9]

positivos = []
negativos = []
zeros = []

for numero in numeros:
    if numero > 0:
        positivos.append(numero)
    elif numero < 0:
        negativos.append(numero)
    else:
        zeros.append(numero)

print("Lista original:", numeros)
print("Positivos:", positivos)
print("Negativos:", negativos)
print("Zeros:", zeros)

"""Exercicio 26 - Aqui a calculadora ela ira recebe dois numeros e a operação escolhida pelo usuario, o programa verifica a divisao por zero para impedif um erro durante a execução"""

numero1 = float(input("Digite o primeiro número: "))
operacao = input("Digite a operação (+, -, * ou /): ")
numero2 = float(input("Digite o segundo número: "))

if operacao == "+":
    resultado = numero1 + numero2
    print("Resultado:", resultado)

elif operacao == "-":
    resultado = numero1 - numero2
    print("Resultado:", resultado)

elif operacao == "*":
    resultado = numero1 * numero2
    print("Resultado:", resultado)

elif operacao == "/":
    if numero2 != 0:
        resultado = numero1 / numero2
        print("Resultado:", resultado)
    else:
        print("Não é possível dividir por zero.")

else:
    print("Operação inválida.")

"""Exercicio 27 - Usei a função sortedx ela coloca as letras em ordem"""

palavra1 = input("Digite a primeira palavra: ")
palavra2 = input("Digite a segunda palavra: ")

palavra1 = palavra1.lower().replace(" ", "")
palavra2 = palavra2.lower().replace(" ", "")

if sorted(palavra1) == sorted(palavra2):
    print("As palavras são anagramas.")
else:
    print("As palavras não são anagramas.")]

"""Exercicio 28 - USei o metodo matplotlib que permite criar graficos, e chamei a função plt.bar para criar o grafico"""

import matplotlib.pyplot as plt

quantidade = int(input("Quantas categorias serão adicionadas? "))

categorias = []
valores = []

for contador in range(quantidade):
    categoria = input(f"Digite o nome da categoria {contador + 1}: ")
    valor = float(input(f"Digite o valor de {categoria}: "))

    categorias.append(categoria)
    valores.append(valor)

plt.bar(categorias, valores, color="royalblue")

plt.title("Gráfico de barras")
plt.xlabel("Categorias")
plt.ylabel("Valores")
plt.show()

"""Exercicio 29- Aqui utilizei a fizzBuzz a ele percorre os numeros de 1 a 100 com algumas regras."""

for numero in range(1, 101):
    if numero % 3 == 0 and numero % 5 == 0:
        print("FizzBuzz")
    elif numero % 3 == 0:
        print("Fizz")
    elif numero % 5 == 0:
        print("Buzz")
    else:
        print(numero)

"""Exercicio 30"""

import random

palavras = ["python", "computador", "programacao", "algoritmo"]
palavra_secreta = random.choice(palavras)

letras_corretas = set()
letras_erradas = set()
tentativas = 6

print("Bem-vindo ao jogo da forca!")

while tentativas > 0:
    palavra_exibida = ""

    for letra in palavra_secreta:
        if letra in letras_corretas:
            palavra_exibida += letra + " "
        else:
            palavra_exibida += "_ "

    print("\nPalavra:", palavra_exibida)
    print("Letras erradas:", letras_erradas)
    print("Tentativas restantes:", tentativas)

    if all(letra in letras_corretas for letra in palavra_secreta):
        print("Parabéns! Você descobriu a palavra.")
        break

    palpite = input("Digite uma letra: ").lower()

    if len(palpite) != 1 or not palpite.isalpha():
        print("Digite somente uma letra.")
        continue

    if palpite in letras_corretas or palpite in letras_erradas:
        print("Essa letra já foi utilizada.")
        continue

    if palpite in palavra_secreta:
        letras_corretas.add(palpite)
        print("Você acertou uma letra!")
    else:
        letras_erradas.add(palpite)
        tentativas -= 1
        print("Essa letra não está na palavra.")

else:
    print("Suas tentativas acabaram.")
    print("A palavra era:", palavra_secreta)

"""Exercicio 31"""

numeros = [8, 4, 2, 9, 5, 1]

print("Lista original:", numeros)

tamanho = len(numeros)

for i in range(tamanho):
    for j in range(0, tamanho - i - 1):
        if numeros[j] > numeros[j + 1]:
            temporario = numeros[j]
            numeros[j] = numeros[j + 1]
            numeros[j + 1] = temporario

print("Lista ordenada:", numeros)

"""exercicio 32

"""

def mostrar_tabuleiro(tabuleiro):
    print()
    print(tabuleiro[0], "|", tabuleiro[1], "|", tabuleiro[2])
    print("--+---+--")
    print(tabuleiro[3], "|", tabuleiro[4], "|", tabuleiro[5])
    print("--+---+--")
    print(tabuleiro[6], "|", tabuleiro[7], "|", tabuleiro[8])
    print()


def verificar_vitoria(tabuleiro, jogador):
    combinacoes = [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 3, 6],
        [1, 4, 7],
        [2, 5, 8],
        [0, 4, 8],
        [2, 4, 6]
 ]dor_atual} venceu!")
        break

    if jogador_atual == "X":
        jogador_atual = "O"
    else:
        jogador_atual = "X"

else:
    mostrar_tabuleiro(tabuleiro)
    print("O jogo terminou empatado.")

"""Exericio 33"""

palavra1 = input("Digite a primeira palavra: ")
palavra2 = input("Digite a segunda palavra: ")

palavra1 = palavra1.lower().replace(" ", "")
palavra2 = palavra2.lower().replace(" ", "")

letras1 = sorted(palavra1)
letras2 = sorted(palavra2)

if letras1 == letras2:
    print("As palavras são anagramas.")
else:
    print("As palavras não são anagramas.")

"""Exercicio 34


"""

texto = input("Digite uma frase: ").lower()

vogais = "aeiou"
quantidade = 0

for caractere in texto:
    if caractere in vogais:
        quantidade += 1

print("Quantidade de vogais:", quantidade)

"""Exercicio 35

"""

limite = int(input("Digite o valor limite: "))

primeiro = 0
segundo = 1

print(f"Sequência de Fibonacci até {limite}:")

while primeiro <= limite:
    print(primeiro)

    proximo = primeiro + segundo
    primeiro = segundo
    segundo = proximo

"""Exercicio 36"""

import random
import string

tamanho = int(input("Digite o tamanho da senha: "))

caracteres = string.ascii_letters + string.digits
senha = ""

for contador in range(tamanho):
    senha += random.choice(caracteres)

print("Senha gerada:", senha)

"""Exercicio 37

"""

def calcular_fatorial(numero):
    if numero == 0 or numero == 1:
        return 1

    return numero * calcular_fatorial(numero - 1)


numero = int(input("Digite um número inteiro não negativo: "))

if numero < 0:
    print("Não existe fatorial de número negativo.")
else:
    resultado = calcular_fatorial(numero)
    print(f"O fatorial de {numero} é {resultado}.")

"""Exercicio 38"""

texto = input("Digite um texto: ")

palavras = texto.split()
quantidade = len(palavras)

print("Palavras encontradas:", palavras)
print("Quantidade de palavras:", quantidade)

"""Exercicio 39"""

import random

dado1 = random.randint(1, 6)
dado2 = random.randint(1, 6)

soma = dado1 + dado2

print("Resultado do primeiro dado:", dado1)
print("Resultado do segundo dado:", dado2)
print("Soma dos dados:", soma)

"""Exercicio 40"""

lista_compras = []

while True:
    print("\nLISTA DE COMPRAS")
    print("1 - Adicionar item")
    print("2 - Remover item")
    print("3 - Listar itens")
    print("4 - Sair")

    opcao = input("Escolha uma opção: ")

    if opcao == "1":
        item = input("Digite o item que deseja adicionar: ")
        lista_compras.append(item)
        print(f"{item} foi adicionado.")

    elif opcao == "2":
        item = input("Digite o item que deseja remover: ")

        if item in lista_compras:
            lista_compras.remove(item)
            print(f"{item} foi removido.")
        else:
            print("O item não foi encontrado.")

    elif opcao == "3":
        if len(lista_compras) == 0:
            print("A lista está vazia.")
        else:
            print("\nItens da lista:")

            for numero, item in enumerate(lista_compras, start=1):
                print(f"{numero} - {item}")

    elif opcao == "4":
        print("Programa encerrado.")
        break

    else:
        print("Opção inválida.")

"""Exercicio 41"""

numeros = [5, 2, 5, 8, 2, 10, 8, 3]

sem_duplicatas = []

for numero in numeros:
    if numero not in sem_duplicatas:
        sem_duplicatas.append(numero)

print("Lista original:", numeros)
print("Lista sem duplicatas:", sem_duplicatas)

"""Exercicio 42"""

limite = int(input("Digite o valor limite: "))

primos = []

for numero in range(2, limite + 1):
    eh_primo = True

    for divisor in range(2, int(numero ** 0.5) + 1):
        if numero % divisor == 0:
            eh_primo = False
            break

    if eh_primo:
        primos.append(numero)

print(f"Números primos até {limite}:")
print(primos)

"""Exercicio 43"""

metros = float(input("Digite o valor em metros: "))

print("1 - Converter para centímetros")
print("2 - Converter para quilômetros")
print("3 - Converter para milímetros")

opcao = input("Escolha uma opção: ")

if opcao == "1":
    resultado = metros * 100
    print(f"{metros} metros equivalem a {resultado} centímetros.")

elif opcao == "2":
    resultado = metros / 1000
    print(f"{metros} metros equivalem a {resultado} quilômetros.")

elif opcao == "3":
    resultado = metros * 1000
    print(f"{metros} metros equivalem a {resultado} milímetros.")

else:
    print("Opção inválida.")]

"""Exercicio 44"""

quantidade = int(input("Digite a quantidade de termos: "))

primeiro = 0
segundo = 1

if quantidade <= 0:
    print("Digite uma quantidade maior que zero.")
else:
    print("Sequência de Fibonacci:")

    for contador in range(quantidade):
        print(primeiro)

        proximo = primeiro + segundo
        primeiro = segundo
        segundo = proximo

"""Exercicio 45"""

numeros = [5, 8, 12, 7, 3, 20, 14, 9]

pares = []
impares = []

for numero in numeros:
    if numero % 2 == 0:
        pares.append(numero)
    else:
        impares.append(numero)

print("Lista original:", numeros)
print("Números pares:", pares)
print("Números ímpares:", impares)

"""Exercicio 46"""

numeros = [10, 12, 14, 16, 18]

media = sum(numeros) / len(numeros)

soma_diferencas = 0

for numero in numeros:
    diferenca = numero - media
    soma_diferencas += diferenca ** 2

variancia = soma_diferencas / len(numeros)
desvio_padrao = variancia ** 0.5

print("Lista:", numeros)
print(f"Média: {media:.2f}")
print(f"Desvio padrão: {desvio_padrao:.2f}")

"""Exercicio 47"""

numeros = [2, 5, 2, 8, 5, 2, 10, 8, 5]

contagem = {}

for numero in numeros:
    if numero in contagem:
        contagem[numero] += 1
    else:
        contagem[numero] = 1

print("Lista:", numeros)
print("Quantidade de ocorrências:")

for numero, quantidade in contagem.items():
    print(f"O número {numero} aparece {quantidade} vez(es).")

"""Exercicio 48"""

numeros = [9, 5, 1, 4, 3, 8]

print("Lista original:", numeros)

for i in range(1, len(numeros)):
    valor_atual = numeros[i]
    j = i - 1

    while j >= 0 and numeros[j] > valor_atual:
        numeros[j + 1] = numeros[j]
        j -= 1

    numeros[j + 1] = valor_atual

print("Lista ordenada:", numeros)

"""Exercicio 49"""

numero = int(input("Digite um número inteiro: "))

numero_positivo = abs(numero)
soma = 0

for digito in str(numero_positivo):
    soma += int(digito)

print(f"A soma dos dígitos de {numero} é {soma}.")

"""Exercicio 50"""

texto = input("Digite uma frase: ").lower()

frequencia = {}

for caractere in texto:
    if caractere.isalpha():
        if caractere in frequencia:
            frequencia[caractere] += 1
        else:
            frequencia[caractere] = 1

print("Frequência das letras:")

for letra, quantidade in sorted(frequencia.items()):
    print(f"{letra}: {quantidade}")